import 'package:flutter/material.dart';

class AppColors {
  static const Color mainColor = const Color(0xFFD34141);
  static const Color orange = const Color(0xFFFE582A);
  static const Color rating_back = const Color(0xFFF88B51);
  static const Color food_rating = const Color(0xFFFFF4e1);
  static const Color greenLight = const Color(0xFFe7fff5);
  static const Color green = const Color(0xFF27ae60);
  static const Color ora = const Color(0xFFfff4e1);
  static const Color oragd = const Color(0xFFffb845);
  static const Color ambiance = const Color(0xFFfbf1ff);
  static const Color ambiancedark = const Color(0xFFa700ff);
  static const Color pricing = const Color(0xFFfff1fe);
  static const Color pricingdark = const Color(0xFFff7cc8);
  static const Color start = const Color(0xFFFE582A);
  static const Color price = const Color(0xFF27ae60);
  static const Color light = const Color(0xFFFF8b90);
  static const Color appbar = const Color(0xFFFF5931);
  static const Color blue = const Color(0xFF2457cf);
  static const Color black = const Color(0xFF000000);
  static const Color white = const Color(0xFFFFFFFF);
  static const Color black54 = const Color(0xFF212121);
  static const Color start_color = const Color(0xFFfb8f57);
  static const Color end_color = const Color(0xFFA22636);
  static const Color end_color1 = const Color(0xFFfde4df);
  static const Color end_color2 = const Color(0xFFfffdfd);
  static const Color text = const Color(0xFF6c02ad);
  static const Color start3 = const Color(0xFF7327ae);
  static const Color end = const Color(0xFFf5f5f5);
  static const Color bg = const Color(0xFFFCEEE8);
  static const Color bg_background2 = const Color(0xFF1D0C08);
  static const Color bg_background3 = const Color(0xFF482119);
  static const Color bg_background4 = const Color(0xFF493834);
  static const Color cream = const Color(0xFFFFF8F6);
  static const Color offers = const Color(0xFF503b38);
  static const Color start_splash = const Color(0xFFF89860);
  static const Color end_splash = const Color(0xFFF67538);
  static const Color bg_pink = const Color(0xFFF2ecf1);
  static const Color bluee = const Color(0xFF2F80ED);
  static const Color gstart = const Color(0xFFFFF8f6);
  static const Color g2 = const Color(0x0FFFBF0F7);
  static const Color ge = const Color(0x0FFFFF8F7);
  static const Color or = const Color(0x0FFFE582A);
  static const Color purple = const Color(0x0FFA700FF);
}
